apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://localhost:6443
    name: demo-cluster

contexts:
  - context:
      cluster: demo-cluster
      namespace: demo-namespace
    name: demo

current-context: demo
