apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://localhost:6443
    name: demo-cluster

users:
  - name: alice
  - name: bob

contexts:
  - context:
      cluster: demo-cluster
      namespace: demo-namespace
      user: alice
    name: alice-context
  - context:
      cluster: demo-cluster
      namespace: demo-namespace
      user: bob
    name: bob-context

current-context: alice-context
