apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      certificate-authority-data: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtekNDQVVDZ0F3SUJBZ0lVTnRRLzlhd282
        aDRXbGpscS93SXlhYytIMVhNd0NnWUlLb1pJemowRUF3SXcKRWpFUU1BNEdBMVVFQXd3SFkyeDFj
        M1JsY2pBZ0Z3MHlOakF6TWpZeE9USTVNVGhhR0E4eU1EVXpNRGd4TVRFNQpNamt4T0Zvd0VqRVFN
        QTRHQTFVRUF3d0hZMngxYzNSbGNqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFC
        RForZncrWmlWMzlaSTVZbTBBaXVYL3Q0a01BNmtyR2pJUVNKc01ROUtlNlp2eTNkUWw3SlhFdlBr
        WkQKUlBRK20zWktoVUcxL1BrZDZDR1FEMFBwSEdhamNqQndNQjBHQTFVZERnUVdCQlFFaVN4aUs5
        bi9IQ0ltc0owOQp1OFdyeFYreU1EQWZCZ05WSFNNRUdEQVdnQlFFaVN4aUs5bi9IQ0ltc0owOXU4
        V3J4Vit5TURBUEJnTlZIUk1CCkFmOEVCVEFEQVFIL01CMEdBMVVkRVFRV01CU0NCMk5zZFhOMFpY
        S0NDV3h2WTJGc2FHOXpkREFLQmdncWhrak8KUFFRREFnTkpBREJHQWlFQW41OG5YOWhoZ3QrdUc1
        TjRtNVFpYmdkeGg4MUNRL1ZXbjNmZURBa2tVUG9DSVFEbAp3NEdkbGI2TmRpREdGb1FkcklkdDdP
        UXNoR1FZeVlrRDVqa25qVmFxemc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://localhost:6443
    name: demo-cluster

contexts:
  - context:
      cluster: demo-cluster
      namespace: demo-namespace
    name: demo

current-context: demo
