apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
  - claimMappings:
      username:
        claim: email
        prefix: "oidc:"
      groups:
        claim: groups
        prefix: "oidc:"
    issuer:
      url: https://localhost:8443
      audiences:
        - authorization-code-mock-client
      certificateAuthority: |
        -----BEGIN CERTIFICATE-----
        MIIDGjCCAgKgAwIBAgIUXgM4UcedQK2hC/CIXyAvJVNUsJYwDQYJKoZIhvcNAQEL
        BQAwDjEMMAoGA1UEAwwDaWRwMCAXDTI2MDMyNTIxNDcxNloYDzIwNTMwODEwMjE0
        NzE2WjAOMQwwCgYDVQQDDANpZHAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
        AoIBAQCc+CtA2n7MAPpXfHplrx2kVDzLExbDQWemQSB0U6RsQNaYl/UdorJC3G86
        McUPkye8pPrRWgIMBntSITaxZkOifgmY9JiGn+iNVab50ZhEFG/9/MmeOt6eGzxp
        KSBmOcx/xa96giFNTWZ9yfgvmeuttQjnWvtDxfLwX5+4wlp97xfTIZrxb09Sn6Yu
        EroTbMMlOVHPIHUUSPshBjwMMqLbkPEraT7dON6MC8QiLdRdAq0p7ZjhatAbCuhq
        h+68NSQaL8lei4RuxJTEHIC6aY9M05j9Y/310VfbBVshs5FDo33h8QDHuGp8a9NL
        sJry/t98ObaWOwnHiO7MSR9sE/TpAgMBAAGjbjBsMB0GA1UdDgQWBBTLfAUIisZw
        40LkCWZG6mHz39bzvDAfBgNVHSMEGDAWgBTLfAUIisZw40LkCWZG6mHz39bzvDAP
        BgNVHRMBAf8EBTADAQH/MBkGA1UdEQQSMBCCA2lkcIIJbG9jYWxob3N0MA0GCSqG
        SIb3DQEBCwUAA4IBAQAXTyy7MleNWHTd/IxleLypo3722wkvIbrtH7gO5GtjO+Y9
        LNanrHot3lKZmpL08YHWpUexi/4c5j1/MN91LNHTb75MyQfuHd2xHTuwQxRVJp/C
        gi01O9oZscOKBTyTN7F8iRsTEMeupEwCcm4rZPmHCRYTlkiftmXNDpZCL62NPonN
        iq4XHm085TPss7tkvpzIz+Z2PlNqHYZDr/GKpWQ/c2h6plIm75CsitkxxpYeCb4x
        nXnY6Rexzktu5qyWo2tBONi7aII9vl4lrJkprDSpE8sjBFS+NWw3LfIM+JTzGWtS
        RQVnlx4sw6Qss10Gp0v8ZGpEVh4FB1IyqZKNOVYo
        -----END CERTIFICATE-----
