users:
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://localhost:8443
          - --oidc-client-id=mock-client
          - --oidc-extra-scope=openid,profile,email
        command: kubectl
        interactiveMode: Never

contexts:
  - context:
      cluster: demo-cluster
      namespace: demo-namespace
      user: oidc
    name: demo-kubelogin

current-context: demo-kubelogin
