apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-role
  namespace: demo-namespace
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-rolebinding
  namespace: demo-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitor-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: oidc:monitor
